Repository carbon-design-system/design-language-website, pull requests merged in 2019-07, with the labels that each got.

#105 fix: homepage style bugs
  src/components/HomepageTile/_homepage-tile.scss
  src/components/HomepageVideo/_homepage-video.scss
  src/pages/index.mdx
Labels: status: ready for review :eyes:

#103 fix: color switcher style bugs
  src/components/SwatchPaletteWidget/SwatchPaletteWidget.js
  src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
  src/pages/elements/color.mdx
Labels: status: ready for review :eyes:, status: visual review :eyes:

#104 feat: add link to bottom of left hand nav
  src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
Labels: status: one more review :eyes:, status: ready for review :eyes:

#115 Update SVG
  src/pages/elements/icons/images/sizing-alignment-example-comp.svg
Labels: status: one more review :eyes:

#111 chore: update carbon dependencies
  .yarn-offline-mirror/@carbon-colors-10.3.0.tgz
  .yarn-offline-mirror/@carbon-elements-10.4.0.tgz
  .yarn-offline-mirror/@carbon-grid-10.4.0.tgz
  .yarn-offline-mirror/@carbon-icon-helpers-0.0.1-beta.5.tgz
  .yarn-offline-mirror/@carbon-icon-helpers-10.2.0.tgz
  .yarn-offline-mirror/@carbon-icon-helpers-10.3.0.tgz
  .yarn-offline-mirror/@carbon-icons-10.4.0.tgz
  .yarn-offline-mirror/@carbon-icons-react-0.0.1-beta.5.tgz
  .yarn-offline-mirror/@carbon-icons-react-10.3.0.tgz
  .yarn-offline-mirror/@carbon-icons-react-10.4.0-alpha.5407.tgz
  .yarn-offline-mirror/@carbon-icons-react-10.4.0-alpha.5467.tgz
  .yarn-offline-mirror/@carbon-icons-react-10.4.1.tgz
  .yarn-offline-mirror/@carbon-import-once-10.3.0.tgz
  .yarn-offline-mirror/@carbon-layout-10.3.0.tgz
  .yarn-offline-mirror/@carbon-motion-10.3.0.tgz
  .yarn-offline-mirror/@carbon-themes-10.4.0.tgz
  .yarn-offline-mirror/@carbon-type-10.3.0.tgz
  .yarn-offline-mirror/@vimeo-player-2.10.0.tgz
  .yarn-offline-mirror/carbon-components-10.2.0.tgz
  .yarn-offline-mirror/carbon-components-10.3.2.tgz
  .yarn-offline-mirror/carbon-components-10.4.1.tgz
  .yarn-offline-mirror/carbon-components-react-7.2.0.tgz
  .yarn-offline-mirror/carbon-components-react-7.3.2.tgz
  .yarn-offline-mirror/carbon-components-react-7.4.1.tgz
  .yarn-offline-mirror/flatpickr-4.5.5.tgz
  .yarn-offline-mirror/flatpickr-4.5.7.tgz
  .yarn-offline-mirror/gatsby-mdx-0.6.3.tgz
  .yarn-offline-mirror/gatsby-plugin-mdx-1.0.13.tgz
  .yarn-offline-mirror/gatsby-theme-carbon-1.4.0.tgz
  .yarn-offline-mirror/gatsby-theme-carbon-1.6.0.tgz
  .yarn-offline-mirror/lodash-4.17.14.tgz
  .yarn-offline-mirror/native-promise-only-0.8.1.tgz
  .yarn-offline-mirror/p-queue-5.0.0.tgz
  .yarn-offline-mirror/prism-react-renderer-0.1.7.tgz
  .yarn-offline-mirror/weakmap-polyfill-2.0.0.tgz
  package.json
  yarn.lock
Labels: status: one more review :eyes:

#117 fix: update favicon
  gatsby-config.js
  src/images/favicon-512.png
Labels: status: one more review :eyes:, status: visual review :eyes:

#126 chore: sync icon-library with carbon
  src/components/IconLibrary/IconLibrary.js
  src/components/IconLibrary/icon-library.scss
  src/pages/elements/icon-library.mdx
  src/pages/images/GitHubIcon.svg
Labels: status: ready for review :eyes:, status: visual review :eyes:

#118 fix: remove video container cta margin override
  src/components/HomepageVideo/_homepage-video.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#116 fix: match color blocks to spec
  src/pages/elements/color-ui.mdx
  src/styles/_color.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#106 fix: carousel spacing at mobile
  src/components/Carousel/_carousel.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#107 fix: typeface page styles and include Carbon Slider
  src/components/TypeFaceSubFamilies/_typeface-sub-families.scss
  src/components/TypeTester/TypeTester.js
  src/components/TypeTester/_type-tester.scss
  src/pages/elements/typeface.mdx
Labels: status: one more review :eyes:, status: visual review :eyes:
