Repository carbon-design-system/design-language-website, pull requests merged in 2019-08, with the labels that each got.

#113 fix(TypesetStyle): use default Carbon slider
  src/components/InputRange/InputRange.js
  src/components/InputRange/_input-range.scss
  src/components/InputRange/index.js
  src/components/TypesetStyle/TypesetStyle.js
  src/components/TypesetStyle/_typeset-style.scss
  src/styles/index.scss
Labels: status: ready for review :eyes:, status: visual review :eyes:

#119 chore: content updates on pictograms page
  src/pages/elements/pictograms/images/02_Padding_2_do.svg
  src/pages/elements/pictograms/images/02_Padding_3_dont.svg
  src/pages/elements/pictograms/images/06_Corners_1.svg
  src/pages/elements/pictograms/images/10_Backgrounds_5_dont.svg
  src/pages/elements/pictograms/overview.mdx
  src/pages/elements/pictograms/usage.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:, type: content :book:

#143 fix: replace broken and placeholder links
  src/pages/elements/pictograms/overview.mdx
  src/pages/index.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:

#144 fix(gatsby-config): append MDX frontmatter title
  gatsby-config.js
Labels: status: one more review :eyes:, status: ready for review :eyes:

#137 fix(typeface-sub-families): use Carbon outline styles
  src/components/TypeFaceSubFamilies/_typeface-sub-families.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#142 feat(ColorGrid): introduce ColorGrid component
  src/components/ColorGrid/ColorGrid.js
  src/components/ColorGrid/_color-grid.scss
  src/components/ColorGrid/index.js
  src/pages/elements/color-ui.mdx
  src/pages/elements/color.mdx
  src/pages/elements/images/color-grid-alert.png
  src/pages/elements/images/color-grid-blues.png
  src/pages/elements/images/color-grid-full.png
  src/pages/elements/images/color-grid-grays.png
  src/styles/index.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#139 fix(philosophy): enable fluid type mixin
  src/styles/_philosophy.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#158 chore: remove unnecessary the in rebus.mdx
  src/pages/elements/logos/rebus.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:

#152 fix(homepage-video): reset mobile margin
  src/components/HomepageVideo/_homepage-video.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#163 Chore: add mobile images to /logos/8-bar and /photography/tips-and-techniques
  src/pages/elements/logos/8-bar.mdx
  src/pages/elements/logos/images/8bar-legal-mobile.svg
  src/pages/elements/photography/tips-and-techniques.mdx
Labels: status: one more review :eyes:

#168 chore: add mobile images to type-basics.mdx
  src/pages/elements/images/Duo_Mobile_TypeBasics_Line_lengths_within_containers_do.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Line_lengths_within_containers_dont.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Rags_orphans_and_widows_do_01.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Rags_orphans_and_widows_do_02.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Rags_orphans_and_widows_dont_01.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Rags_orphans_and_widows_dont_02.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Stacked_headlines_do.svg
  src/pages/elements/images/Duo_Mobile_TypeBasics_Stacked_headlines_dont.svg
  src/pages/elements/images/modern-and-sharp-right-mobile.svg
  src/pages/elements/images/modern-and-sharp-wrong-center-mobile.svg
  src/pages/elements/images/modern-and-sharp-wrong-center.svg
  src/pages/elements/images/modern-and-sharp-wrong-double-mobile.svg
  src/pages/elements/images/modern-and-sharp-wrong-double.svg
  src/pages/elements/images/modern-and-sharp-wrong-mobile.svg
  src/pages/elements/images/this-is-comfortable-mobile.svg
  src/pages/elements/images/this-is-too-comfortable-mobile.svg
  src/pages/elements/images/this-is-uncomfortable-mobile.svg
  src/pages/elements/type-basics.mdx
Labels: status: one more review :eyes:

#153 fix(non-latin-script): avoid script cutoff
  src/components/NonLatinScripts/_non-latin-script.scss
  src/components/TypeFaceSubFamilies/TypefaceSubFamilies.js
  src/components/TypeTester/TypeTester.js
Labels: status: ready for review :eyes:, status: visual review :eyes:

#173 fix: typo
  src/pages/elements/logos/8-bar.mdx
Labels: status: ready for review :eyes:

#174 fix(pictograms): rename page
  src/data/nav-items.yaml
  src/pages/elements/pictograms/contribute.mdx
  src/pages/elements/pictograms/design.mdx
  src/pages/elements/pictograms/usage.mdx
Labels: status: ready for review :eyes:

#175 fix(icons): rename page
  src/data/nav-items.yaml
  src/pages/elements/app-icons/usage.mdx
  src/pages/elements/icons/contribute.mdx
  src/pages/elements/icons/design.mdx
  src/styles/_icons.scss
Labels: status: ready for review :eyes:

#176 fix(homepage-video): change default flex-basis
  src/components/HomepageVideo/_homepage-video.scss
Labels: status: ready for review :eyes:, status: visual review :eyes:

#180 fix(non-latin-script): increase line height for non latin type examples
  src/components/NonLatinScripts/_non-latin-script.scss
Labels: status: ready for review :eyes:, status: visual review :eyes:

#185 fix(pictograms): add links for design and production guidelines
  src/pages/elements/pictograms/contribute.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:

#187 fix(typeface-sub-families): avoid line breaks on mobile
  src/components/TypeFaceSubFamilies/_typeface-sub-families.scss
Labels: status: ready for review :eyes:

#171 Chore: adds mobile images to pictograms design page
  12_TintsShades_2-mobile_1.svg
  src/pages/elements/pictograms/design.mdx
  src/pages/elements/pictograms/images/02_Padding_1_base_grid-mobile.svg
  src/pages/elements/pictograms/images/03_Style_1-mobile.svg
  src/pages/elements/pictograms/images/03_Style_2-mobile.svg
  src/pages/elements/pictograms/images/03_Style_3-mobile.svg
  src/pages/elements/pictograms/images/03_Style_4-mobile.svg
  src/pages/elements/pictograms/images/03_Style_5-mobile.svg
  src/pages/elements/pictograms/images/03_Style_6-mobile.svg
  src/pages/elements/pictograms/images/03_Style_7-mobile.svg
  src/pages/elements/pictograms/images/03_Style_8-mobile.svg
  src/pages/elements/pictograms/images/04_Strokes_1-mobile.svg
  src/pages/elements/pictograms/images/06_Corners_1-mobile_1.svg
  src/pages/elements/pictograms/images/06_Corners_2.svg
  src/pages/elements/pictograms/images/07_Angles_1-mobile.svg
  src/pages/elements/pictograms/images/07_Angles_2-mobile_1.svg
  src/pages/elements/pictograms/images/09_Color_1-mobile.svg
  src/pages/elements/pictograms/images/09_Color_2-mobile.svg
  src/pages/elements/pictograms/images/09_Color_3-mobile.svg
  src/pages/elements/pictograms/images/10_Backgrounds-mobile_1.svg
  src/pages/elements/pictograms/images/11_Gradients_1-mobile-1.svg
  src/pages/elements/pictograms/images/11_Gradients_2-mobile-1.svg
  src/pages/elements/pictograms/images/12_TintsShades_1-mobile_1.svg
  src/pages/elements/pictograms/images/12_TintsShades_2-mobile_1.svg
  src/pages/elements/pictograms/images/32x32-base-grid-comp-mobile.svg
  src/pages/elements/pictograms/usage.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:

#186 [app icons/2x grid] Mobile Image Updates
  src/pages/elements/2x-grid.mdx
  src/pages/elements/app-icons/design.mdx
  src/pages/elements/app-icons/images/2_2-1_NativeOS_Containers1.svg
  src/pages/elements/app-icons/images/2_2-1_NativeOS_Containers1_Mobile_v2.svg
  src/pages/elements/app-icons/images/2_2-1_NativeOS_Containers1_v2.svg
  src/pages/elements/app-icons/images/2_2-2_NativeOS_Containers2_Mobile_v2.svg
  src/pages/elements/app-icons/images/2_2-2_NativeOS_Containers2_v2.svg
  src/pages/elements/app-icons/images/3_3-3_ExportingProduct_Stroke_Step4.png
  src/pages/elements/app-icons/images/3_3-4_ExportingProduct_Stroke_Step5.svg
  src/pages/elements/app-icons/images/3_3-6_ExportingProduct_Fill_Step4.png
  src/pages/elements/app-icons/images/3_3-7_ExportingProduct_Fill_Step5.svg
  src/pages/elements/app-icons/production.mdx
  src/pages/elements/app-icons/usage.mdx
  src/pages/elements/images/Mobile-mini-unit-all.svg
  src/pages/elements/images/Mobile_SpatialRelationships.svg
Labels: status: one more review :eyes:

#177 fix: whitespace on Philosophy/POV page
  src/pages/philosophy/pov.mdx
  src/styles/_philosophy.scss
Labels: blocked, status: WIP 👩‍💻, status: visual review :eyes:

#172 fix(TypeTester): reduce default slider value for smaller screens
  src/components/TypeTester/TypeTester.js
Labels: status: ready for review :eyes:, status: visual review :eyes:

#194 fix(TypesetStyle): add class to style controls when stuck
  src/components/TypesetStyle/TypesetStyle.js
Labels: status: ready for review :eyes:, status: visual review :eyes:

#170 fix(index): resolve homepage layout bugs
  src/components/Carousel/_carousel.scss
  src/components/HomepageTile/HomepageTile.js
  src/pages/index.mdx
Labels: status: ready for review :eyes:, status: visual review :eyes:

#204 chore: remove Disciplines pages and assets
  src/data/nav-items.yaml
  src/pages/disciplines/digital.mdx
  src/pages/disciplines/images/bee.svg
  src/pages/disciplines/images/carbon-10.png
  src/pages/disciplines/images/component-library-img1.png
  src/pages/disciplines/images/component-library-img2.png
  src/pages/disciplines/images/digital-component-library-img1.png
  src/pages/disciplines/images/digital-component-library-img2.png
  src/pages/disciplines/images/digital-design-kit-img1.png
  src/pages/disciplines/images/digital-design-kit-img2.png
  src/pages/disciplines/images/product-design-kit-img1.png
  src/pages/disciplines/images/product-design-kit-img2.png
  src/pages/disciplines/product.mdx
Labels: status: ready for review :eyes:

#205 chore: remove intro text from icon library page
  src/pages/elements/icon-library.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:

#230 feat: update deployment config to deploy live
  .circleci/config.yml
Labels: status: ready for review :eyes:

#244 fix(principles): bold entire sentence
  src/pages/philosophy/principles.mdx
Labels: status: ready for review :eyes:

#242 fix(typeface): use correct hyperlink
  src/pages/elements/typeface.mdx
Labels: status: ready for review :eyes:

#247 fix(Carousel): use camelcased autoplay attribute
  src/components/Carousel/Carousel.js
  src/pages/elements/color.mdx
  src/pages/index.mdx
Labels: status: ready for review :eyes:

#253 fix: update thai-looped classname
  src/components/TypeTester/TypeTester.js
  src/pages/gallery.mdx
Labels: status: one more review :eyes:

#257 chore: add styles for ibm inserted cookie prefs button
  src/styles/_ibm-cookies.scss
  src/styles/index.scss
Labels: status: ready for review :eyes:
