Repository carbon-design-system/design-language-website, pull requests merged in 2019-09, with the labels that each got.

#270 fix(type-basics): fix video poster
  src/pages/elements/type-basics.mdx
Labels: status: ready for review :eyes:

#269 fix(type-basics): alignment copy edit
  src/pages/elements/type-basics.mdx
Labels: status: ready for review :eyes:

#268 fix(color): update broken resources and hyperlinks
  src/pages/elements/color.mdx
  src/pages/elements/images/introduction.gif
Labels: status: one more review :eyes:, status: ready for review :eyes:

#267 fix(typeface): use more specific hyperlink
  src/pages/elements/typeface.mdx
Labels: status: one more review :eyes:

#271 fix(color-page): prevent carousel from collapsing on mobile
  src/components/Carousel/_carousel.scss
  src/styles/_homepage.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#274 fix(SwatchPaletteWidget): restore format switching functionality
  src/components/SwatchPaletteWidget/SwatchPaletteWidget.js
Labels: status: ready to merge 🎉

#277 docs: fix icon size typo
  src/pages/elements/icons/usage.mdx
Labels: status: one more review :eyes:, status: ready for review :eyes:

#285 chore: update dependancies
  yarn.lock
Labels: status: failing tests :no_good_man:
