Repository carbon-design-system/design-language-website, pull requests merged in 2019-10, with the labels that each got.

#324 fixed icon dimensions
  src/components/SvgLibraries/shared/SvgLibrary.module.scss
Labels: status: one more review :eyes:

#319 Added pictograms resource card
  src/pages/elements/pictograms/design.mdx
Labels: status: one more review :eyes:

#329 fix: pictogram usage gallery
  src/pages/elements/pictograms/images/18_In-Context_5.jpg
  src/pages/elements/pictograms/images/18_In-Context_7.svg
  src/pages/elements/pictograms/usage.mdx
Labels: status: ready to merge 🎉

#312 Sticky search
  src/components/SvgLibraries/IconLibrary/IconLibrary.js
  src/components/SvgLibraries/PictogramLibrary/PictogramLibrary.js
  src/components/SvgLibraries/shared/FilterRow.js
  src/components/SvgLibraries/shared/SvgLibrary.module.scss
  src/lib/useSticky.js
Labels: status: visual review :eyes:
