Repository carbon-design-system/design-language-website, pull requests merged in 2020-01, with the labels that each got.

#405 pictograms-design content changes
  src/pages/iconography/pictograms/design.mdx
Labels: status: ready to merge 🎉

#410 Fix/intro description
  src/pages/iconography/app-icons/design.mdx
  src/pages/iconography/app-icons/production.mdx
  src/pages/iconography/app-icons/usage.mdx
  src/pages/iconography/pictograms/contribute.mdx
  src/pages/iconography/pictograms/design.mdx
  src/pages/iconography/pictograms/usage.mdx
  src/pages/iconography/ui-icons/contribute.mdx
  src/pages/iconography/ui-icons/design.mdx
  src/pages/iconography/ui-icons/usage.mdx
Labels: status: one more review 👀

#413 fix(images): replace broken and outdated images
  src/pages/ibm-logos/8-bar.mdx
  src/pages/ibm-logos/images/logo_alignments.svg
  src/pages/iconography/pictograms/images/06_Corners_1-mobile_1.svg
  src/pages/iconography/pictograms/images/07_Angles_2-mobile_1.svg
  src/pages/iconography/pictograms/images/11_Gradients_1-mobile-1.svg
  src/pages/iconography/pictograms/images/11_Gradients_2-mobile-1.svg
  src/pages/iconography/pictograms/images/12_TintsShades_1-mobile_1.svg
  src/pages/iconography/pictograms/images/12_TintsShades_2-mobile_1.svg
  src/pages/iconography/ui-icons/design.mdx
  src/styles/_images.scss
Labels: status: one more review 👀, status: visual review 🔍

#417 Fix typo
  src/pages/ibm-logos/8-bar.mdx
Labels: status: one more review 👀

#408 [Layout - tips and techniques] Update description
  src/pages/layout/tips-and-techniques.mdx
Labels: status: one more review 👀

#403 Layout page: Update Garage image
  src/pages/layout/images/Garage.png
Labels: status: ready to merge 🎉
